### ISSUE TITLE
Excluding paths via pre-commit / wrongly targeted files

### ISSUE THREAD

**Issue by GitRon** [adamchainz/djade#64]
### Description

Dear @adamchainz 

Thx for this amazing package! Just threw it on a 12 year old codebase and it looks great!

Just one thing that came up: I use helm charts in my repo and it started reformatting a file in `charts/my-project/templates`. The odd thing is, the file is no HTML file but a `.tpl`.

I'm not that familiar with pre-commit (I just use it 😅 ) and wasn't able to configure it.

I see two scenarios here:

1. Maybe it targets *.tpl files by accient?
2. Maybe I have to configure that I don't want the helm charts directory. Then, for other people as stupid as me, a hint in the Readme on how to do that would be amazing

**Supplemental:** It also tries rewriting this file: `Rewriting apps/account/tests/templates/test_template_employee_detail.py`

Thx for all the hard work! ❤️

Ronny

**Comment by adamchainz** [comment]
The default configuration targets all files in all directories called `templates`. (And I just pushed [this commit](https://github.com/adamchainz/djade-pre-commit/commit/384ca3e5fefc7fc4f43730d53ac1aa2bfe94047f) that will limit it to text files in the next release.)

It's deliberately not limited to HTML files because templates are often used for other file formats too, like text files for emails or CSS for user-customizable themes.

You can exclude your problematic files like:

```yaml
- repo: https://github.com/adamchainz/djade-pre-commit
  rev: 1.0.0
  hooks:
    - id: djade
      exclude: |
        (?x)^(
          charts/.*
          |.*\.py
        )$
```

I will look at writing a blog post on pre-commit's exclusion mechanisms, then linking it.
