### ISSUE TITLE
Usage with HTML formatter in parralel?

### ISSUE THREAD

**Issue by ddahan** [adamchainz/djade#74]
### Description

Thanks a lot for this package!
Not really a feature request, but I was wondering what would be the recommendation to handle HTML formatting in addition to Django formatting, using Djade.
For example, could I run prettier first then Djade? Or the opposite?
Thanks.

**Comment by adamchainz** [comment]
I don't know right now. I haven't had much luck using HTML formatters, and I'm sceptical about the possibility of formatting correctly.

Last I checked, Prettier's HTML formatting fails on Django templates. I know there's a plugin: https://til.simonwillison.net/npm/prettier-django .

And I don't think that HTML can be correctly formatted without edge cases. Whitespace can be meaningful in any part of an HTML document thanks to CSS `white-space: pre`, or at least desirable in multiline attributes like https://github.com/rtts/djhtml/issues/92 .

Anyway, if using a formatter, I think running Djade first will make the most sense. Its edits are mostly restricted to the insides of Django tags.

**Comment by UnknownPlatypus** [comment]
@ddahan I've built [djangofmt](https://github.com/UnknownPlatypus/djangofmt) a django template formater that is html aware. 

You can run it along djade in pre-commit like so (I test in CI this combinaison explicitely to ensure it converges)

```yaml
repos:
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.9.0"
    hooks:
      - id: djade
  - repo: https://github.com/UnknownPlatypus/djangofmt-pre-commit
    rev: v1.0.0
    hooks:
      - id: djangofmt
```

Might help you there
