### ISSUE TITLE
Source configuration from pyproject.toml

### ISSUE THREAD

**Issue by christophehenry** [adamchainz/djade#77]
### Description

Current usage is `djade --target-version 5.1 templates/**/*.html`. It would be awesome if `djade` could be configured in `pyproject.toml` like so:

```toml
[tool.djade]
files = [
    "templates/**/*.html"
]
target_version = "5.1"
```
